package algonquin.cst2335.finalandroidproject.Trivia;

import androidx.appcompat.app.AppCompatActivity;

import android.annotation.SuppressLint;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.TextView;

import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import androidx.room.Room;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executor;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import algonquin.cst2335.finalandroidproject.R;
import algonquin.cst2335.finalandroidproject.databinding.ActivityQuizBinding;
import algonquin.cst2335.finalandroidproject.databinding.ActivityTriviaBinding;
import algonquin.cst2335.finalandroidproject.databinding.FragmentScoresBinding;
import algonquin.cst2335.finalandroidproject.databinding.ScoreItemBinding;

/**
 * Activity for managing the quiz gameplay. This class displays questions and manages the player's score.
 * Users can respond to quiz questions, view their current score, and submit their final score.
 * The activity also interfaces with a local Room database to save scores and fetch top scores for the leaderboard.
 * <p>
 * Key Components:
 * - RecyclerView: To display the list of questions.
 * - ScoreTextView: Displays the current score.
 * - SharedPreferences: Persists user preferences/settings.
 * - QuestionDatabase and QuizQuestionDAO: Interfaces with the Room database for CRUD operations.
 * </p>
 */
public class QuizActivity extends AppCompatActivity {

    private RecyclerView recyclerView;
    private ArrayList<QuestionObj> questions;
    private TextView scoreTextView;
    private SharedPreferences sharedPreferences;
    private int score = 0;
    private QuizQuestionDAO quizQuestionDAO;
    protected ActivityQuizBinding binding;
    protected ActivityTriviaBinding variableBinding;

    protected ScoreItemBinding variableBindings;
    private TriviaActivity.ScoreAdapter scoreAdapter;


    @SuppressLint("MissingInflatedId")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Intent intent = getIntent();
        String userName = intent.getStringExtra("UserName");
        setContentView(R.layout.activity_quiz);

        ActivityQuizBinding binding = ActivityQuizBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());


        QuestionDatabase db = Room.databaseBuilder(getApplicationContext(),
                        QuestionDatabase.class, "question-database")
                .fallbackToDestructiveMigration()
                .build();
        quizQuestionDAO = db.qqDAO();

        scoreTextView = binding.scoreTextView;

        sharedPreferences = getSharedPreferences("MyPrefs", MODE_PRIVATE);


        scoreTextView = binding.scoreTextView;
        scoreTextView.setText("Score: " + score); // initial score



        recyclerView = binding.recyclerView;
        recyclerView.setLayoutManager(new LinearLayoutManager(this));

        ArrayList<QuestionObj> questions = (ArrayList<QuestionObj>) getIntent().getSerializableExtra("questions");
        if (questions != null) {
            recyclerView.setAdapter(new TriviaActivity.QuestionAdapter(questions));
        } else {
            Log.e("QuizActivity", "Questions list is null");
            // handle error condition here...
        }
        Button finishQuizButton = binding.quizDoneButton;

        finishQuizButton.setOnClickListener(new View.OnClickListener() {


            @Override
            public void onClick(View view) {
                Log.d("SubmitButton", "Button clicked!");

                String userCategory = "N/A";
                final Score scoreObj = new Score(0, userName, score, userCategory); // '0' for id implies it should be autogenerated

                ExecutorService executorService = Executors.newSingleThreadExecutor();
                // Insert the score and delete another score (if necessary) on a background thread
                executorService.execute(new Runnable() {
                    @Override
                    public void run() {
                        // Insert the new score
                        quizQuestionDAO.insert(scoreObj);

                        // For illustration, let's say you want to delete scores below a certain value
                        int thresholdScore = 5;
                        quizQuestionDAO.deleteScoresBelowValue(thresholdScore); // This DAO method needs to be defined

                        // Now fetch the top scores
                        List<Score> scores = quizQuestionDAO.getTopScores();
                        Log.d("Database Fetch", "Scores Size: " + scores.size());

                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                Intent intent = new Intent(QuizActivity.this, LeaderBoardActivity.class);
                                intent.putExtra("scores", new ArrayList<>(scores)); // put the scores into the intent
                                startActivity(intent);
                            }
                        });
                    }
                });
            }
        });
    }

                                                public void incrementScore() {
                                                    this.score++;
                                                    scoreTextView.setText("Score: " + this.score); // Update the TextView text
                                                }
                                            }








    // Display score method